menu:
    Blog: /
    Archive: /archives/
    Twitter: https://twitter.com/CageChung
    GitHub: https://github.com/cage1016
    Slideshare: http://www.slideshare.net/cagechung
    Linkedin: https://www.linkedin.com/in/kaichuchung
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus: kaichuio
duoshuo:

# Analytics
# google-analytics:
ga: UA-65308340-1

# Copyright Infomation
startyear: 2015
